name: naver_login_sdk
description: "Flutter Naver Login SDK Package. Naver is a leading web service in South Korea."
version: 1.0.6
repository: https://github.com/hamhoney/flutter_naver_login_sdk/tree/main/packages/NaverLoginSDK

environment:
  sdk: ^3.5.3
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  flutter_logcat: ^1.2.10
  picture_button: ^0.1.1
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
screenshots:
  - description: Naver Open Resource
    path: screenshots/naver_rectangle_icon.png

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/en/dark/
    - assets/en/green/
    - assets/en/logout/
    - assets/en/white/
    - assets/kr/dark/
    - assets/kr/green/
    - assets/kr/white/
    - assets/kr/logout/


  plugin:
    platforms:
      android:
        package: net.lagerstroemia.naver_login_sdk
        pluginClass: NaverLoginSdkPlugin
      ios:
        pluginClass: NaverLoginSdkPlugin